version: '3.8'

services:

  app:
    image: tribe:latest
    user: "${UID}:${GID}"
    network_mode: bridge
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tribe
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_VK_CLIENT_ID: ${VK_CLIENT_ID}
      SPRING_VK_CLIENT_SECRET: ${VK_CLIENT_SECRET}
      SPRING_VK_API_VERSION: ${VK_API_VERSION}
      SPRING_VK_INTROSPECTION_URI: ${VK_INTROSPECTION_URI}
      SPRING_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_LOG_DIRECTORY: ${LOG_DIRECTORY}
      SPRING_PARENT_DIRECTORY: ${PARENT_DIRECTORY}
      SPRING_WHATSAPP_API_HOST: ${WHATSAPP_API_HOST}
      SPRING_WHATSAPP_API_VERSION: ${WHATSAPP_API_VERSION}
      SPRING_WHATSAPP_ACCESS_TOKEN: ${WHATSAPP_ACCESS_TOKEN}
      SPRING_WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      SPRING_DADATA_TOKEN: ${DADATA_API_KEY}
      APP_PORT: ${APP_PORT}
      JAVA_TOOL_OPTIONS: "-XX:MaxDirectMemorySize=256m"
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    restart: always
    volumes:
      - ~/tribe:/tribe
      - ~/tribe/logs:/tribe/logs

  db:
    image: postgis/postgis
    network_mode: bridge
    container_name: "db"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tribe
    ports:
      - "127.0.0.1:${EXTERNAL_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d tribe" ]
      interval: 8s
      timeout: 4s
      retries: 4

volumes:
  pg_data:
