version: '3.8'

services:

  app:
    image: docker-spring-boot-postgres:latest
    network_mode: bridge
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: "app"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tribe
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ~/tribe:/tribe

  db:
    image: postgis/postgis
    network_mode: bridge
    container_name: "db"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tribe
    ports:
      - "${EXTERNAL_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d tribe" ]
      interval: 8s
      timeout: 4s
      retries: 4

volumes:
  pg_data: