server:
  port: ${APP_PORT}

spring:
  cloud:
    openfeign:
      client:
        config:
          vk-client:
            url: ${SPRING_VK_INTROSPECTION_URI}
            client-id: ${SPRING_VK_CLIENT_ID}
            client-secret: ${SPRING_VK_CLIENT_SECRET}
            api-version: ${SPRING_VK_API_VERSION}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show_sql: true
    open-in-view: true #lock auto start transactional anywhere
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  mail:
    host: mail.jino.ru
    port: 587
    username: tribe@tribual.ru
    password: M5T&ojn@PF$Czx*b
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
        starttls:
          enable: true
  flyway:
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

logging:
  level:
    root: info
  file:
    path: ${SPRING_LOG_DIRECTORY}

# swagger
springdoc:
  default-produces-media-type: application/json

path:
  home: ${SPRING_PARENT_DIRECTORY}
  main: tribe
  tmp: temp
  image: image
  avatar: avatar
  event: event
  user: user

keys:
  access-private: access_private.der
  access-public: access_public.pem
  refresh-private: refresh_private.der
  refresh-public: refresh_public.pem
google:
#  client-id: 407408718192.apps.googleusercontent.com for tests Nikita
  client-id: ${SPRING_GOOGLE_CLIENT_ID}

