spring:
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration,
    org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration,
    org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration"
  properties:
    hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  jpa:
#    database-platform: com.covenant.tribe.configuration.CustomPostgreSQLDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    openfeign:
      client:
        config:
          kudago-client:
            connectTimeout: 100000
            readTimeout: 100000
            error-decoder: com.covenant.tribe.client.kudago.decoder.KudagoDecoder
            retryer: com.covenant.tribe.client.kudago.retryer.KudagoClientRetryer
          dadata-client:
            url: "https://suggestions.dadata.ru"
            defaultRequestHeaders:
              Content-Type: application/json
              Accept: application/json
              Authorization: ${SPRING_DADATA_TOKEN}
            connectTimeout: 100000
            readTimeout: 100000
          kudago-image-client:
            url: "https://media.kudago.com/"
            connectTimeout: 50000
            readTimeout: 50000
            retryer: com.covenant.tribe.client.kudago.retryer.KudagoClientRetryer

elastic:
  enabled: false
scheduler:
  mode: "retrying"
event:
  message:
    strategy: CONSOLE