server:
  port: 8085

spring:
  elasticsearch:
    rest:
      uris: mock
  cloud:
    openfeign:
      client:
        config:
          vk-client:
            url: mock
            client-id: 777
            client-secret: 777
            api-version: 777
          whatsapp-client:
            logger-level: full
            url: mock
            api-version: 777
            access-token: mock
            phone-number-id: 777
          kudago-client:
            url: "https://kudago.com/public-api/v1.4"
  jpa:
    show_sql: true
    open-in-view: false #lock auto start transactional anywhere
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  mail:
    host: mail.jino.ru
    port: 587
    username: tribe@tribual.ru
    password: M5T&ojn@PF$Czx*b
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
        starttls:
          enable: true


# swagger
springdoc:
  default-produces-media-type: application/json

path:
  home: ${SPRING_PARENT_DIRECTORY}
  main: tribe
  tmp: temp
  image: image
  avatar: avatar
  event: event
  user: user
  animation: animation
  add-events: add events
  onboard: onboard

keys:
  access-private: access_private.der
  access-public: access_public.pem
  refresh-private: refresh_private.der
  refresh-public: refresh_public.pem
google:
  #  client-id: 407408718192.apps.googleusercontent.com for tests Nikita
  client-id: mock

logging:
  level:
    root: info
    com:
      covenant:
        tribe:
          service:
            impl: debug
verification:
  code:
    email:
      min: 1000
      max: 9999