spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
allowed:
  cors:
    - https://dev.tribual.ru
    - https://dev.admin.tribual.ru/
    - http://localhost
    - http://localhost:3000
logging:
  level:
    org.springframework.security: trace
path:
  main: tribe/dev
