spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
allowed:
  corse:
    tribual: https://dev.tribual.ru
    admin: https://dev.admin.tribual.ru/
    host: http://localhost
    admin-host: http://localhost:3001
path:
  main: tribe/dev
