spring:
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration,
    org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration,
    org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration"
  properties:
    hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  jpa:
#    database-platform: com.covenant.tribe.configuration.CustomPostgreSQLDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    openfeign:
      client:
        config:
          kudago-client:
            connectTimeout: 100000
            readTimeout: 100000
            error-decoder: com.covenant.tribe.client.kudago.decoder.KudagoDecoder
            retryer: com.covenant.tribe.client.kudago.retryer.KudagoClientRetryer

elastic:
  enabled: false
scheduler:
  mode: "retrying"
