server:
  port: ${APP_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show_sql: true
    open-in-view: true #lock auto start transactional anywhere
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true #откладывает инициализацию данных в бд, пока хибер не сделает таблицы
  sql:
    init:
      mode: always #unlock init sql from data.sql
      continue-on-error: true

logging:
  level:
    root: info

# swagger
springdoc:
  default-produces-media-type: application/json

