CREATE TABLE IF NOT EXISTS event_addresses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude     DOUBLE PRECISION                        NOT NULL,
    longitude    DOUBLE PRECISION                        NOT NULL,
    country      VARCHAR(100),
    city         VARCHAR(100)                            NOT NULL,
    region       VARCHAR(100),
    street       VARCHAR(100),
    district     VARCHAR(100),
    building     VARCHAR(10),
    house_number VARCHAR(10),
    floor        VARCHAR(10),
    CONSTRAINT pk_event_addresses PRIMARY KEY (id)
);

