CREATE TABLE IF NOT EXISTS event_addresses
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude  DOUBLE PRECISION                        NOT NULL,
    longitude DOUBLE PRECISION                        NOT NULL,
    city_id   BIGINT,
    street    VARCHAR(100),
    house     VARCHAR(10),
    building  VARCHAR(10),
    floor     VARCHAR(3),
    CONSTRAINT pk_event_addresses PRIMARY KEY (id)
);

