CREATE TABLE email_verification_code
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reset_code   INTEGER                                 NOT NULL,
    email        VARCHAR(100)                            NOT NULL,
    request_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_enable    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_email_verification_code PRIMARY KEY (id)
);

DROP TABLE reset_codes CASCADE;