INSERT INTO event_types(type_name)
VALUES ('concert'),
       ('music'),
       ('sport'),
       ('party'),
       ('stand_up'),
       ('science'),
       ('business'),
       ('books'),
       ('child'),
       ('art');

INSERT INTO tags(tag_name)
VALUES ('techno'),
       ('rock'),
       ('pop'),
       ('hip-hop'),
       ('metal'),
       ('cycling'),
       ('running'),
       ('sailing'),
       ('hockey'),
       ('ping_pong'),
       ('volleyball'),
       ('football'),
       ('basketball'),
       ('poker'),
       ('chess'),
       ('boxing'),
       ('wing_chun'),
       ('skateboarding'),
       ('street_art'),
       ('chemistry'),
       ('physics'),
       ('math'),
       ('in_nature');