INSERT INTO event_types(type_name)
VALUES ('sport'),
       ('transportation'),
       ('exhibition'),
       ('party'),
       ('education'),
       ('music'),
       ('for children'),
       ('countryside retreat'),
       ('religion'),
       ('cinema'),
       ('festivals');

INSERT INTO tags(tag_name)
VALUES ('cycling'),
       ('running'),
       ('sailing'),
       ('hockey'),
       ('ping pong'),
       ('volleyball'),
       ('football'),
       ('basketball'),
       ('poker'),
       ('chess'),
       ('boxing'),
       ('wing chun'),
       ('skateboarding'),
       ('chemistry'),
       ('physics'),
       ('math'),
       ('cars'),
       ('motorcycles'),
       ('garage'),
       ('tuning'),
       ('excursions'),
       ('museums'),
       ('bar'),
       ('restaurant'),
       ('apartment'),
       ('pub'),
       ('board games'),
       ('medical'),
       ('it'),
       ('coaches'),
       ('artists'),
       ('moms and dads'),
       ('concert'),
       ('disco'),
       ('philharmonic'),
       ('piano'),
       ('rock'),
       ('metal'),
       ('pop'),
       ('rap'),
       ('hip hop');

INSERT INTO event_type_tags(type_id, tag_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 10),
       (1, 11),
       (1, 12),
       (1, 13),
       (5, 14),
       (5, 15),
       (5, 16),
       (2, 17),
       (2, 18),
       (2, 19),
       (3, 20),
       (3, 21),
       (3, 22),
       (4, 23),
       (4, 24),
       (4, 25),
       (4, 26),
       (4, 27),
       (5, 28),
       (5, 29),
       (5, 30),
       (5, 31),
       (5, 32),
       (6, 33),
       (6, 34),
       (6, 35),
       (6, 36),
       (6, 37),
       (6, 38),
       (6, 39),
       (6, 40),
       (6, 41);