CREATE TABLE contact_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contact_type VARCHAR(255),
    contact      TEXT,
    CONSTRAINT pk_contact_info PRIMARY KEY (id)
);

CREATE TABLE event_contact_info
(
    contact_info_id BIGINT NOT NULL,
    event_id        BIGINT NOT NULL
);

ALTER TABLE event_contact_info
    ADD CONSTRAINT fk_eveconinf_on_event FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE event_contact_info
    ADD CONSTRAINT fk_eveconinf_on_event_contact_info FOREIGN KEY (contact_info_id) REFERENCES contact_info (id);