CREATE TABLE chat
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_group BOOLEAN,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

CREATE TABLE message
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(255),
    author_id BIGINT,
    chat_id   BIGINT,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE event_contact_info
    ADD CONSTRAINT pk_event_contact_info PRIMARY KEY (contact_info_id, event_id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);