CREATE TABLE last_read_message
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id        BIGINT,
    participant_id BIGINT,
    message_id     BIGINT,
    CONSTRAINT pk_last_unread_message PRIMARY KEY (id)
);

ALTER TABLE last_read_message
    ADD CONSTRAINT FK_LAST_UNREAD_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE last_read_message
    ADD CONSTRAINT FK_LAST_UNREAD_MESSAGE_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES message (id);

ALTER TABLE last_read_message
    ADD CONSTRAINT FK_LAST_UNREAD_MESSAGE_ON_PARTICIPANT FOREIGN KEY (participant_id) REFERENCES users (id);