CREATE TABLE profession
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_profession PRIMARY KEY (id)
);

CREATE TABLE user_profession
(
    profession_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    CONSTRAINT pk_user_profession PRIMARY KEY (profession_id, user_id)
);

ALTER TABLE profession
    ADD CONSTRAINT uc_profession_name UNIQUE (name);

ALTER TABLE user_profession
    ADD CONSTRAINT fk_usepro_on_profession FOREIGN KEY (profession_id) REFERENCES profession (id);

ALTER TABLE user_profession
    ADD CONSTRAINT fk_usepro_on_user FOREIGN KEY (user_id) REFERENCES users (id);